const express = require('express');
const wardAdminRoleController = require('../../controllers/wardAdminRole.controller');
const router = express.Router();

router.route('/').post(wardAdminRoleController.createwardAdminRoleService);
router.route('/:date').get(wardAdminRoleController.getAllwardAdminRole);
router.route('/getAllData/:id').get(wardAdminRoleController.getDataById);
router.route('/createwardAdminRoleAsm/data').post(wardAdminRoleController.createwardAdminRoleAsmService);
router.route('/data/:id').get(wardAdminRoleController.getAllWardAdminRoleData);
router.route('/smData/data/:date').get(wardAdminRoleController.smData);
router.route('/totalChange/:id').put(wardAdminRoleController.total);
router.route('/createAsmSamesman').post(wardAdminRoleController.createAsmSalesman);
router.route('/getAllSalesmanData/:id').get(wardAdminRoleController.allAsmSalesmanData);
router.route('/getAllAssignReassign/:id').get(wardAdminRoleController.getAllAssignReassignData);
router.route('/createSalesmanShop').post(wardAdminRoleController.createSalesmanShop);
router.route('/data/getAllAssignSalesmanShopData/data/:id').get(wardAdminRoleController.getAllAssignSalesmanShopData);
router.route('/getAllSalesMandataCurrentdate/:id').get(wardAdminRoleController.getAllSalesMandataCurrentdate);
router.route('/createwithoutoutAsmSalesman').post(wardAdminRoleController.createwithoutoutAsmSalesman);
router.route('/withoutoutAsmSalesmanCurrentDate/:id').get(wardAdminRoleController.withoutoutAsmSalesmanCurrentDate);
router.route('/withoutoutAsmSalesman/data/:date').get(wardAdminRoleController.withoutoutAsmSalesman);
router.route('/dataAllSalesManhistry/:id').get(wardAdminRoleController.dataAllSalesManhistry);
router.route('/allocateDeallocateCount/:id').get(wardAdminRoleController.allocateDeallocateCount);
router.route('/createtemperaryAssigndata').post(wardAdminRoleController.createtemperaryAssigndata);
router.route('/getAllTempReassigndata/data').get(wardAdminRoleController.getAllTempReassigndata);
router.route('/getAssign/dataBy/salesMan/:page').get(wardAdminRoleController.getAssignData_by_SalesMan);
router.route('/getAssign/dataBy/salesMan/Id/:id').get(wardAdminRoleController.get_Assign_data_By_SalesManId);
router.route('/getData/without/given/:id').get(wardAdminRoleController.getUsersWith_skiped);
router.route('/Return_Assign_To_SalesMan/:id').get(wardAdminRoleController.Return_Assign_To_SalesMan);
router.route('/history_Assign_Reaasign_data/:id/:date/:idSearch/:tempid').get(wardAdminRoleController.history_Assign_Reaasign_data);
router.route('/getAllSalesmanShops/data').get(wardAdminRoleController.getAllSalesmanShops);
router.route('/getAllSalesmanShopsData/data/:id').get(wardAdminRoleController.getAllSalesmanShopsData);
router.route('/getDataAll/data').get(wardAdminRoleController.getDataAll);
router.route('/getAllAsmCurrentdata/data/:id').get(wardAdminRoleController.getAllAsmCurrentdata);
router.route('/createwithAsmwithoutAsm/data').post(wardAdminRoleController.createwithAsmwithoutAsm);
router.route('/getwithAsmwithoutAsm/data/:type/:date').get(wardAdminRoleController.getwithAsmwithoutAsm);
router.route('/WardAdminRoleHistor/:id/:date').get(wardAdminRoleController.WardAdminRoleHistor);
router.route('/getAllWithAsmwithout/:sm/:asm/:date').get(wardAdminRoleController.getAllWithAsmwithout);
router.route('/asmdata/data').get(wardAdminRoleController.asmdata);
router.route('/asmSalesman/data/:id').get(wardAdminRoleController.asmSalesman);
router.route('/telecallerHead/data').get(wardAdminRoleController.telecallerHead);
module.exports = router;
