module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.customerService = require('./customer.service');
module.exports.BusinessService = require('./businessDetails.service');
module.exports.VendorService = require('./vendor.service');
module.exports.sampleService = require('./sample.Service');
module.exports.sloggerService = require('./slogger.service');
module.exports.categoryService = require('./category.service');
module.exports.ProductComboService = require('./productCombo.service');
module.exports.categoryService = require('./category.service');
module.exports.cartManagementService = require('./cartManagement.service');
module.exports.wardService = require('./ward.service');
module.exports.cartManagementService = require('./cartManagement.service');
module.exports.street = require('./street.service');
module.exports.zone= require('./zone.service');
module.exports.district= require('./district.service');
module.exports.deliveryAddress= require('./deliveryAddress.service');
module.exports.receiveOrdersService = require('./receivedOrders.service');
module.exports.manageScvService = require('./manageSCVOrders.service')
module.exports.warehouseStock = require('./warehouseStock..service.')
module.exports.loadingExecuteService = require('./loading.execute.service');
module.exports.RolesService = require('./roles.sservice');
module.exports.menuesService = require('./menue.service');
module.exports.supplierService = require('./supplier.service')